version: "3"
services:
  kong-auth-ui:
    image: sebwink/kong-auth-ui
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - '3000:3000/tcp'
    volumes:
      - '../../src:/app/src'
      - '../../public:/app/public'
      - '../../config:/app/config'
      - '../../scripts:/app/scripts'
